name: docable CI
on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install bakerx
      run: sudo npm install -g ottomatica/bakerx
    - name: Ensure we have base image.
      run: bakerx pull ottomatica/bakerx#images bionic-node
    - name: Install Docker
      run: |
        brew install docker docker-machine
        curl --create-dirs -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        docker-machine create --driver virtualbox default

    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: |
        eval $(docker-machine env default)
        npm test
